### PR TITLE
building in tmp to avoid bloating container

### PR DESCRIPTION
**Pull request by GodloveD**
Should be self-explanatory.

### CODE REVIEW

**Review by shahzebsiddiqui — COMMENTED** [review]
There are a few concerns, BUILD_DIR should be changed to something inside the container to avoid running out of space. 

I think you are confusing --robot with --robot-paths, --robot is used for building the app with all the dependency and --robot-paths is used to find all the easyconfig files for dependency resolution if your easyconfigs are in different path. By default --robot-paths when installed with pip is /usr/easybuild/easyconfigs so you don't have to setup --robot-paths since it is setup automatically. You do need to setup --robot if you want to build your entire dependency tree.

Line 21: MODULEPATH would need to be adjusted depending on which module naming scheme you use, by default Flat Naming Scheme will work with your setting, but preferably we should look at Hierarchical Module Naming Scheme (HMNS) to avoid long module names and improved user-interaction. For that case MODULEPATH will be altered slightly.

Line 22-31 Lmod translation to sh is too complex, its not a good idea to do this and let Lmod manage the environment. The overhead of having a module file is minimal

**Comment by GodloveD** [comment]
Thanks for the feedback @shahzebsiddiqui.  Let me reply to your comments.

The location of `BUILD_DIR` is a pickle.  For instance in tests building gcc 5.0 inside a container we were seeing that you needed to create a container that was 15 GB in size even though the actual meat of the container only ends up being ~2.5 GB.  If you build inside of a container you also have to clean up src files afterward.  This sounds like a pain.  But I agree `/tmp` might not be best place either.  I think `/scratch` is better, but we can't be sure that `/scratch` exists on a given system.  So for now, I'm thinking `/tmp` is the best alternative and it will be up to the user to make sure they have enough space in `/tmp` to build.

Thanks for your suggestions on `--robot`.  So you mean I basically just need the `--robot` flag with no directory and I should be good to go right?  I will make that change.

As for your final 2 concerns, first I don't think it makes sense to have a hierarchical module system within a container.  One container should be for one app.  If you want to access one of the dependancies as it's own app, you should install it in a new container of it's own.  

For that reason, I really don't like the idea of using Lmod inside the container much.  There may be a few special circumstances, but in general I think EB and Lmod should be uninstalled from the container when bootstrap concludes and that is what I'm working toward here.  For your particular needs we can talk about whether we want that or not.  But for the EB community version I'm thinking of here, I think I'm going to stick with setting env up and getting rid of Lmod and EB.

**Comment by shahzebsiddiqui** [comment]
I understand the problem with storage and over allocating space in container,  but it is probably worth than having your container fail because it runs out of space. Container should be reproducible irrespective of system environment. This means, we can't make assumption that particular mounts exist as each system will have slightly different configuration. /tmp for us is too short only few GB and this will not work for us.

I'd propose to create /scratch inside container as done in https://github.com/easybuilders/eb-singularity/blob/master/Dockerfile and let eb write to this path. Later we can optimize storage by exporting the content of the container into a smaller container.

--robot and --robot-path are two different flags. You just need to specify --robot without any argument, problem is you are cloning easyconfig repo, rather let pip install eb so that --robot is setup properly

If you are inside the container this is what eb should be set.
```
[easybuild@amrndhl1295 ~]$ eb --show-full-config | grep robot
robot                                     (D) = None
robot-paths                               (D) = /usr/easybuild/easyconfigs
```
--robot-path is like the PATH environment but for eb to find easyconfig. This lets you do the following

```
[easybuild@amrndhl1295 ~]$ eb -S binutils-2.26.eb
CFGS1=/usr/easybuild/easyconfigs/b/binutils
 * $CFGS1/binutils-2.26.eb
[easybuild@amrndhl1295 ~]$ eb binutils-2.26.eb -D
== temporary log file in case of crash /tmp/eb-vgHoep/easybuild-7aBn9K.log
Dry run: printing build status of easyconfigs and dependencies
CFGS=/usr/easybuild/easyconfigs
 * [ ] $CFGS/m/M4/M4-1.4.17.eb (module: M4/1.4.17)
 * [ ] $CFGS/b/Bison/Bison-3.0.4.eb (module: Bison/3.0.4)
 * [ ] $CFGS/f/flex/flex-2.6.0.eb (module: flex/2.6.0)
 * [ ] $CFGS/z/zlib/zlib-1.2.8.eb (module: zlib/1.2.8)
 * [ ] $CFGS/b/binutils/binutils-2.26.eb (module: binutils/2.26)
```

Note that if you corrupted your robot path then you would get the following

```
[easybuild@amrndhl1295 ~]$ eb binutils-2.26.eb --robot-paths=/tmp --robot -D
== temporary log file in case of crash /tmp/eb-SkQ5gg/easybuild-JMmAWW.log
ERROR: Can't find path /home/easybuild/binutils-2.26.eb
```

Note the difference between --robot and --robot-path. One adds to the path while the other overwrites the path. 
```
[easybuild@amrndhl1295 ~]$ eb --robot /tmp --show-full-config | grep robot
robot                                     (C) = /tmp, /usr/easybuild/easyconfigs
robot-paths                               (C) = /tmp, /usr/easybuild/easyconfigs
[easybuild@amrndhl1295 ~]$ eb --robot-paths=/home --show-full-config | grep robot
robot                                     (D) = None
robot-paths                               (C) = /home

```

Hierarchical Module vs Flat Naming Scheme will be important in knowing the name of the module file and ultimately how to load it. Granted that if we decide to setup containers without using modules, we still need to load the modules in bootstrap process to find out the content. I was thinking to just capture the environment before/after the module load and just use a diff and append this to /.singularity.d/environment. 

Difference in HMNS and FNS can be shown as follows

FNS note that modulefile are in format %(version)-%(toolchain)
```
[easybuild@amrndhl1295 ~]$ eb OpenMPI-2.1.0-GCC-6.3.0-2.28.eb -x -D
== temporary log file in case of crash /tmp/eb-QgnVos/easybuild-p8QqS9.log
Dry run: printing build status of easyconfigs and dependencies
CFGS=/usr/easybuild/easyconfigs
 * [ ] $CFGS/m/M4/M4-1.4.17.eb (module: M4/1.4.17)
 * [ ] $CFGS/b/Bison/Bison-3.0.4.eb (module: Bison/3.0.4)
 * [ ] $CFGS/f/flex/flex-2.6.0.eb (module: flex/2.6.0)
 * [ ] $CFGS/z/zlib/zlib-1.2.8.eb (module: zlib/1.2.8)
 * [ ] $CFGS/b/binutils/binutils-2.27.eb (module: binutils/2.27)
 * [ ] $CFGS/g/GCCcore/GCCcore-6.3.0.eb (module: GCCcore/6.3.0)
 * [ ] $CFGS/m/M4/M4-1.4.18-GCCcore-6.3.0.eb (module: M4/1.4.18-GCCcore-6.3.0)
 * [ ] $CFGS/z/zlib/zlib-1.2.11-GCCcore-6.3.0.eb (module: zlib/1.2.11-GCCcore-6.3.0)
 * [ ] $CFGS/h/help2man/help2man-1.47.4-GCCcore-6.3.0.eb (module: help2man/1.47.4-GCCcore-6.3.0)
 * [ ] $CFGS/b/Bison/Bison-3.0.4-GCCcore-6.3.0.eb (module: Bison/3.0.4-GCCcore-6.3.0)
 * [ ] $CFGS/f/flex/flex-2.6.3-GCCcore-6.3.0.eb (module: flex/2.6.3-GCCcore-6.3.0)
 * [ ] $CFGS/b/binutils/binutils-2.27-GCCcore-6.3.0.eb (module: binutils/2.27-GCCcore-6.3.0)
 * [ ] $CFGS/n/numactl/numactl-2.0.11-GCCcore-6.3.0.eb (module: numactl/2.0.11-GCCcore-6.3.0)
 * [ ] $CFGS/z/zlib/zlib-1.2.11.eb (module: zlib/1.2.11)
 * [ ] $CFGS/m/M4/M4-1.4.18.eb (module: M4/1.4.18)
 * [ ] $CFGS/h/help2man/help2man-1.47.4.eb (module: help2man/1.47.4)
 * [ ] $CFGS/f/flex/flex-2.6.3.eb (module: flex/2.6.3)
 * [ ] $CFGS/b/binutils/binutils-2.28.eb (module: binutils/2.28)
 * [ ] $CFGS/b/binutils/binutils-2.28-GCCcore-6.3.0.eb (module: binutils/2.28-GCCcore-6.3.0)
 * [ ] $CFGS/g/GCC/GCC-6.3.0-2.28.eb (module: GCC/6.3.0-2.28)
 * [ ] $CFGS/h/hwloc/hwloc-1.11.6-GCC-6.3.0-2.28.eb (module: hwloc/1.11.6-GCC-6.3.0-2.28)
 * [ ] $CFGS/o/OpenMPI/OpenMPI-2.1.0-GCC-6.3.0-2.28.eb (module: OpenMPI/2.1.0-GCC-6.3.0-2.28)

```

In HMNS the modules are stored in directories. For instance M4-1.4.17 is stored in Core/M4/1.4.17

```
[easybuild@amrndhl1295 ~]$ eb OpenMPI-2.1.0-GCC-6.3.0-2.28.eb -D --module-naming-scheme=HierarchicalMNS
== temporary log file in case of crash /tmp/eb-JAARI5/easybuild-YfG4Ec.log
Dry run: printing build status of easyconfigs and dependencies
CFGS=/usr/easybuild/easyconfigs
 * [ ] $CFGS/m/M4/M4-1.4.17.eb (module: Core | M4/1.4.17)
 * [ ] $CFGS/b/Bison/Bison-3.0.4.eb (module: Core | Bison/3.0.4)
 * [ ] $CFGS/f/flex/flex-2.6.0.eb (module: Core | flex/2.6.0)
 * [ ] $CFGS/z/zlib/zlib-1.2.8.eb (module: Core | zlib/1.2.8)
 * [ ] $CFGS/b/binutils/binutils-2.27.eb (module: Core | binutils/2.27)
 * [ ] $CFGS/g/GCCcore/GCCcore-6.3.0.eb (module: Core | GCCcore/6.3.0)
 * [ ] $CFGS/m/M4/M4-1.4.18-GCCcore-6.3.0.eb (module: Compiler/GCCcore/6.3.0 | M4/1.4.18)
 * [ ] $CFGS/z/zlib/zlib-1.2.11-GCCcore-6.3.0.eb (module: Compiler/GCCcore/6.3.0 | zlib/1.2.11)
 * [ ] $CFGS/h/help2man/help2man-1.47.4-GCCcore-6.3.0.eb (module: Compiler/GCCcore/6.3.0 | help2man/1.47.4)
 * [ ] $CFGS/b/Bison/Bison-3.0.4-GCCcore-6.3.0.eb (module: Compiler/GCCcore/6.3.0 | Bison/3.0.4)
 * [ ] $CFGS/f/flex/flex-2.6.3-GCCcore-6.3.0.eb (module: Compiler/GCCcore/6.3.0 | flex/2.6.3)
 * [ ] $CFGS/b/binutils/binutils-2.27-GCCcore-6.3.0.eb (module: Compiler/GCCcore/6.3.0 | binutils/2.27)
 * [ ] $CFGS/n/numactl/numactl-2.0.11-GCCcore-6.3.0.eb (module: Compiler/GCCcore/6.3.0 | numactl/2.0.11)
 * [ ] $CFGS/z/zlib/zlib-1.2.11.eb (module: Core | zlib/1.2.11)
 * [ ] $CFGS/m/M4/M4-1.4.18.eb (module: Core | M4/1.4.18)
 * [ ] $CFGS/h/help2man/help2man-1.47.4.eb (module: Core | help2man/1.47.4)
 * [ ] $CFGS/f/flex/flex-2.6.3.eb (module: Core | flex/2.6.3)
 * [ ] $CFGS/b/binutils/binutils-2.28.eb (module: Core | binutils/2.28)
 * [ ] $CFGS/b/binutils/binutils-2.28-GCCcore-6.3.0.eb (module: Compiler/GCCcore/6.3.0 | binutils/2.28)
 * [ ] $CFGS/g/GCC/GCC-6.3.0-2.28.eb (module: Core | GCC/6.3.0-2.28)
 * [ ] $CFGS/h/hwloc/hwloc-1.11.6-GCC-6.3.0-2.28.eb (module: Compiler/GCC/6.3.0-2.28 | hwloc/1.11.6)
 * [ ] $CFGS/o/OpenMPI/OpenMPI-2.1.0-GCC-6.3.0-2.28.eb (module: Compiler/GCC/6.3.0-2.28 | OpenMPI/2.1.0)

``

**Comment by GodloveD** [comment]
"*I was thinking to just capture the environment before/after the module load and just use a diff and append this to /.singularity.d/environment*"

That's exactly what I'm doing! 😄

**Comment by boegel** [comment]
Good discussion going on here, I like where this is going!

Have we reached consensus on the best approach yet? I'm not sure we have a good solution for the `/tmp` vs `/scratch` debate yet (I can't think of a better option myself right now...).

If we are going to avoid that modules need to be used in order to use the container, then the module naming scheme being used is totally irrelevant, right @shahzebsiddiqui?

**Comment by shahzebsiddiqui** [comment]
closing this PR as this is not relevant anymore

**Pull request closed without merging**
